services:
  - type: web
    name: paper-search-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/download_artifacts.py && uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATA_DIR
        value: data
      - key: FRONTEND_ORIGIN
        value: https://seeker-scholar.vercel.app
      - key: BM25_URL
        value: https://github.com/rc-tharun/SeekerScholar/releases/download/v1.0.0-models/bm25.pkl
      - key: DF_URL
        value: https://github.com/rc-tharun/SeekerScholar/releases/download/v1.0.0-models/df.pkl
      - key: GRAPH_URL
        value: https://github.com/rc-tharun/SeekerScholar/releases/download/v1.0.0-models/graph.pkl
      - key: EMBEDDINGS_URL
        value: https://github.com/rc-tharun/SeekerScholar/releases/download/v1.0.0-models/embeddings.pt

